-- Core Domain Tables
-- This migration creates the main application tables
-- Updated: All primary keys are integers with public_id UUID column
-- Updated: Profiles (was users), Locations (was dispensary_locations), 
-- Products with variants, Modern notification system

-- ============================================================================
-- PRIVATE SCHEMA TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS "private"."keys" (
    "key" text NOT NULL,
    "value" text,
    CONSTRAINT "keys_pkey" PRIMARY KEY ("key")
);

ALTER TABLE "private"."keys" OWNER TO "postgres";

-- ============================================================================
-- UNIFIED TIMESTAMP MANAGEMENT
-- ============================================================================

CREATE OR REPLACE FUNCTION public.manage_timestamps()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.created_at := COALESCE(NEW.created_at, now());
        NEW.updated_at := now();
        RETURN NEW;
    END IF;
    
    IF TG_OP = 'UPDATE' THEN
        NEW.created_at := OLD.created_at;
        NEW.updated_at := now();
        RETURN NEW;
    END IF;
    
    RETURN NEW;
END;
$$;

-- Helper to create the trigger on any table
CREATE OR REPLACE FUNCTION public.create_timestamps_trigger(table_name text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format(
        'CREATE TRIGGER trg_timestamps 
         BEFORE INSERT OR UPDATE ON public.%I 
         FOR EACH ROW EXECUTE FUNCTION public.manage_timestamps()',
        table_name
    );
END;
$$;

-- ============================================================================
-- REFERENCE TABLES (no foreign key dependencies)
-- ============================================================================

-- Roles table
CREATE TABLE IF NOT EXISTS public.roles (
    id integer NOT NULL,
    role varchar(255) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_role_unique UNIQUE (role)
);

ALTER TABLE public.roles OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.roles_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.roles_id_seq OWNER TO postgres;
ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;
ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);

SELECT public.create_timestamps_trigger('roles');

-- States table
CREATE TABLE IF NOT EXISTS public.states (
    id integer NOT NULL,
    abbr text,
    name text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT states_pkey PRIMARY KEY (id)
);

ALTER TABLE public.states OWNER TO postgres;

ALTER TABLE public.states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.states_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

SELECT public.create_timestamps_trigger('states');

-- Regions table
CREATE TABLE IF NOT EXISTS public.regions (
    id integer NOT NULL,
    name varchar(255),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT regions_pkey PRIMARY KEY (id)
);

ALTER TABLE public.regions OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.regions_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.regions_id_seq OWNER TO postgres;
ALTER SEQUENCE public.regions_id_seq OWNED BY public.regions.id;
ALTER TABLE ONLY public.regions ALTER COLUMN id SET DEFAULT nextval('public.regions_id_seq'::regclass);

SELECT public.create_timestamps_trigger('regions');

-- Postal codes table
CREATE TABLE IF NOT EXISTS public.postal_codes (
    id integer NOT NULL,
    country_code varchar(255),
    postal_code varchar(255),
    place_name varchar(255),
    state varchar(255),
    state_code varchar(255),
    county varchar(255),
    county_code varchar(255),
    community varchar(255),
    community_code varchar(255),
    latitude real,
    longitude real,
    accuracy integer,
    geom extensions.geometry,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT postal_codes_pkey PRIMARY KEY (id)
);

ALTER TABLE public.postal_codes OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.postal_codes_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.postal_codes_id_seq OWNER TO postgres;
ALTER SEQUENCE public.postal_codes_id_seq OWNED BY public.postal_codes.id;
ALTER TABLE ONLY public.postal_codes ALTER COLUMN id SET DEFAULT nextval('public.postal_codes_id_seq'::regclass);

SELECT public.create_timestamps_trigger('postal_codes');

-- US Locations table (reference data)
CREATE TABLE IF NOT EXISTS public.us_locations (
    id integer NOT NULL,
    zip_code text,
    city text,
    state text,
    latitude real,
    longitude real,
    classification text,
    population integer,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT us_locations_pkey PRIMARY KEY (id)
);

ALTER TABLE public.us_locations OWNER TO postgres;

ALTER TABLE public.us_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.us_locations_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

SELECT public.create_timestamps_trigger('us_locations');

-- Product feature types table
CREATE TABLE IF NOT EXISTS public.product_feature_types (
    id integer NOT NULL,
    name varchar(255),
    CONSTRAINT product_feature_types_pkey PRIMARY KEY (id),
    CONSTRAINT product_feature_types_name_key UNIQUE (name)
);

ALTER TABLE public.product_feature_types OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.product_feature_types_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.product_feature_types_id_seq OWNER TO postgres;
ALTER SEQUENCE public.product_feature_types_id_seq OWNED BY public.product_feature_types.id;
ALTER TABLE ONLY public.product_feature_types ALTER COLUMN id SET DEFAULT nextval('public.product_feature_types_id_seq'::regclass);

-- Product features table
CREATE TABLE IF NOT EXISTS public.product_features (
    id integer NOT NULL,
    name varchar(255),
    type_id integer REFERENCES public.product_feature_types(id),
    CONSTRAINT product_features_pkey PRIMARY KEY (id)
);

ALTER TABLE public.product_features OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.product_features_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.product_features_id_seq OWNER TO postgres;
ALTER SEQUENCE public.product_features_id_seq OWNED BY public.product_features.id;
ALTER TABLE ONLY public.product_features ALTER COLUMN id SET DEFAULT nextval('public.product_features_id_seq'::regclass);

-- Post tags table
CREATE TABLE IF NOT EXISTS public.post_tags (
    id integer NOT NULL,
    tag varchar(255),
    count integer DEFAULT 1,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT post_tags_pkey PRIMARY KEY (id),
    CONSTRAINT post_tags_tag_key UNIQUE (tag)
);

ALTER TABLE public.post_tags OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.post_tags_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.post_tags_id_seq OWNER TO postgres;
ALTER SEQUENCE public.post_tags_id_seq OWNED BY public.post_tags.id;
ALTER TABLE ONLY public.post_tags ALTER COLUMN id SET DEFAULT nextval('public.post_tags_id_seq'::regclass);

SELECT public.create_timestamps_trigger('post_tags');

-- Cloud files table
CREATE TABLE IF NOT EXISTS public.cloud_files (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    cloudinary_id varchar(255),
    signature varchar(255),
    format varchar(255),
    resource_type varchar(255),
    width integer,
    height integer,
    url varchar(255),
    secure_url varchar(255),
    asset_id varchar(255),
    profile_id integer,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT cloud_files_pkey PRIMARY KEY (id),
    CONSTRAINT cloud_files_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.cloud_files OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.cloud_files_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.cloud_files_id_seq OWNER TO postgres;
ALTER SEQUENCE public.cloud_files_id_seq OWNED BY public.cloud_files.id;
ALTER TABLE ONLY public.cloud_files ALTER COLUMN id SET DEFAULT nextval('public.cloud_files_id_seq'::regclass);

CREATE INDEX idx_cloud_files_public_id ON public.cloud_files(public_id);

SELECT public.create_timestamps_trigger('cloud_files');

-- ============================================================================
-- PROFILES TABLE (replaces users)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    auth_id uuid UNIQUE,
    
    -- Profile type (individual, brand, creator, organization)
    profile_type public.profile_type DEFAULT 'individual' NOT NULL,
    
    -- Basic info
    username varchar(255) UNIQUE,
    display_name varchar(255),
    slug text UNIQUE DEFAULT extensions.uuid_generate_v4()::text,
    bio text,
    avatar_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    banner_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    desktop_banner_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    
    -- Account settings
    role_id integer DEFAULT 10 REFERENCES public.roles(id),
    status text DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'deleted', 'published')),
    is_verified boolean DEFAULT false,
    is_private boolean DEFAULT false,
    
    -- Contact (optional, for brands)
    email varchar(255),
    phone varchar(255),
    contact_email varchar(255),
    contact_phone varchar(255),
    website varchar(255),
    
    -- Social links (JSONB for flexibility)
    social_links jsonb DEFAULT '{}',
    
    -- Business info (NULL for individuals, populated for brands/organizations)
    business_info jsonb DEFAULT NULL,
    
    -- Location
    home_location_id integer REFERENCES public.postal_codes(id),
    last_location_id integer REFERENCES public.postal_codes(id),
    
    -- Profile info
    birthday date,
    founded_date varchar(255),
    
    -- Counts (denormalized for performance)
    follower_count integer DEFAULT 0 NOT NULL,
    following_count integer DEFAULT 0 NOT NULL,
    post_count integer DEFAULT 0 NOT NULL,
    like_count integer DEFAULT 0 NOT NULL,
    stash_count integer DEFAULT 0 NOT NULL,
    product_count integer DEFAULT 0,
    location_count integer DEFAULT 0,
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(display_name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(username, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(bio, '')), 'B')
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    last_seen_at timestamptz,
    
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.profiles OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.profiles_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.profiles_id_seq OWNER TO postgres;
ALTER SEQUENCE public.profiles_id_seq OWNED BY public.profiles.id;
ALTER TABLE ONLY public.profiles ALTER COLUMN id SET DEFAULT nextval('public.profiles_id_seq'::regclass);

CREATE INDEX idx_profiles_public_id ON public.profiles(public_id);
CREATE INDEX idx_profiles_fts ON public.profiles USING gin(fts);
CREATE INDEX idx_profiles_username ON public.profiles(username);
CREATE INDEX idx_profiles_slug ON public.profiles(slug);
CREATE INDEX idx_profiles_role ON public.profiles(role_id);
CREATE INDEX idx_profiles_status ON public.profiles(status) WHERE status != 'active';
CREATE INDEX idx_profiles_auth_id ON public.profiles(auth_id);
CREATE INDEX idx_profiles_type ON public.profiles(profile_type);
CREATE INDEX idx_profiles_business_info ON public.profiles USING gin(business_info) WHERE business_info IS NOT NULL;

SELECT public.create_timestamps_trigger('profiles');

-- Update cloud_files FK to profiles
ALTER TABLE public.cloud_files 
    ADD CONSTRAINT cloud_files_profile_id_fkey 
    FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

-- ============================================================================
-- PRODUCT CATEGORIES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.product_categories (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(255),
    slug varchar(255),
    description varchar(255),
    parent_id integer REFERENCES public.product_categories(id),
    image_id integer REFERENCES public.cloud_files(id),
    product_count integer DEFAULT 0,
    hidden boolean DEFAULT false,
    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(name, '')::text)) STORED,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT product_categories_public_id_key UNIQUE (public_id),
    CONSTRAINT product_categories_name_key UNIQUE (name)
);

ALTER TABLE public.product_categories OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.product_categories_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.product_categories_id_seq OWNER TO postgres;
ALTER SEQUENCE public.product_categories_id_seq OWNED BY public.product_categories.id;
ALTER TABLE ONLY public.product_categories ALTER COLUMN id SET DEFAULT nextval('public.product_categories_id_seq'::regclass);

CREATE INDEX idx_product_categories_public_id ON public.product_categories(public_id);

SELECT public.create_timestamps_trigger('product_categories');

-- ============================================================================
-- PRODUCTS TABLE (with variant support)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.products (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    
    -- Basic info
    name varchar(255),
    slug varchar(255),
    description text,
    category_id integer REFERENCES public.product_categories(id),
    
    -- Status
    status varchar(255) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    is_verified boolean DEFAULT false,
    
    -- Media
    thumbnail_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    cover_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    gallery_urls text[] DEFAULT '{}',
    gallery_sort integer[] DEFAULT '{}'::integer[],
    
    -- Pricing (base/display price)
    base_price decimal(10,2),
    price real,
    currency text DEFAULT 'USD',
    
    -- Variants
    has_variants boolean DEFAULT false,
    
    -- Additional structured data
    attributes jsonb DEFAULT '{}',
    additional_information json DEFAULT '{}',
    
    -- SEO/Marketing
    url text,
    
    -- Counts
    post_count integer DEFAULT 0,
    stash_count integer DEFAULT 0 NOT NULL,
    list_count integer DEFAULT 0 NOT NULL,
    brand_count integer DEFAULT 0,
    
    -- Legacy
    giveawayAmount integer,
    post_id integer,
    cached_brand_names text,
    release_date timestamptz,
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')::text), 'A') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'B')
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    published_at timestamptz,
    
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_public_id_key UNIQUE (public_id),
    CONSTRAINT products_name_key UNIQUE (name)
);

ALTER TABLE public.products OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.products_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.products_id_seq OWNER TO postgres;
ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;
ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);

CREATE INDEX idx_products_public_id ON public.products(public_id);
CREATE INDEX idx_products_fts ON public.products USING gin(fts);
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_status ON public.products(status);
CREATE INDEX idx_products_slug ON public.products(slug);

SELECT public.create_timestamps_trigger('products');

-- ============================================================================
-- PRODUCT VARIANTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.product_variants (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id integer NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    
    -- Variant identification
    sku text UNIQUE,
    name text,
    
    -- Variant-specific attributes
    attributes jsonb DEFAULT '{}',
    
    -- Pricing
    price decimal(10,2) NOT NULL,
    compare_at_price decimal(10,2),
    cost decimal(10,2),
    
    -- Inventory
    inventory_quantity integer DEFAULT 0,
    inventory_policy text DEFAULT 'deny' CHECK (inventory_policy IN ('deny', 'continue')),
    
    -- Status
    is_active boolean DEFAULT true,
    position integer DEFAULT 0,
    
    -- Barcode
    barcode text,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT product_variants_pkey PRIMARY KEY (id),
    CONSTRAINT product_variants_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.product_variants OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.product_variants_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.product_variants_id_seq OWNER TO postgres;
ALTER SEQUENCE public.product_variants_id_seq OWNED BY public.product_variants.id;
ALTER TABLE ONLY public.product_variants ALTER COLUMN id SET DEFAULT nextval('public.product_variants_id_seq'::regclass);

CREATE INDEX idx_product_variants_public_id ON public.product_variants(public_id);
CREATE INDEX idx_product_variants_product ON public.product_variants(product_id);
CREATE INDEX idx_product_variants_sku ON public.product_variants(sku);
CREATE INDEX idx_product_variants_active ON public.product_variants(product_id, is_active) WHERE is_active = true;

SELECT public.create_timestamps_trigger('product_variants');

-- ============================================================================
-- LOCATIONS TABLE (replaces dispensary_locations)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.locations (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    
    -- Ownership
    brand_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    
    -- Basic info
    name varchar(255) NOT NULL,
    slug varchar(255) UNIQUE,
    description text,
    location_type public.location_type DEFAULT 'dispensary',
    
    -- Status
    status varchar(255) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived', 'temporarily_closed')),
    is_verified boolean DEFAULT false,
    is_claimed boolean DEFAULT false,
    
    -- Address
    address_line1 varchar(255),
    address_line2 varchar(255),
    city text,
    state text,
    postal_code_id integer REFERENCES public.postal_codes(id),
    country text DEFAULT 'US',
    
    -- Geolocation (PostGIS)
    coordinates extensions.geography(POINT, 4326),
    
    -- Contact
    phone text,
    email text,
    website text,
    
    -- Social links
    social_links jsonb DEFAULT '{}',
    
    -- Operating hours (structured JSON)
    operating_hours jsonb DEFAULT '{
        "monday": {"open": "09:00", "close": "21:00", "closed": false},
        "tuesday": {"open": "09:00", "close": "21:00", "closed": false},
        "wednesday": {"open": "09:00", "close": "21:00", "closed": false},
        "thursday": {"open": "09:00", "close": "21:00", "closed": false},
        "friday": {"open": "09:00", "close": "21:00", "closed": false},
        "saturday": {"open": "10:00", "close": "20:00", "closed": false},
        "sunday": {"open": "10:00", "close": "18:00", "closed": false}
    }',
    
    -- SEARCHABLE FEATURES (JSONB with GIN index)
    features jsonb DEFAULT '{}',
    
    -- Media
    banner_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    logo_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    gallery_urls text[] DEFAULT '{}',
    
    -- Licenses
    licenses jsonb DEFAULT '[]',
    
    -- Region
    region_id integer REFERENCES public.regions(id),
    
    -- Legacy fields for compatibility
    code varchar DEFAULT public.generate_randome_code(),
    message text,
    about_us text,
    min_age integer,
    member_since integer,
    delivery_radius real,
    delivery_details text,
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(city, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'C')
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT locations_pkey PRIMARY KEY (id),
    CONSTRAINT locations_public_id_key UNIQUE (public_id),
    CONSTRAINT locations_name_unique UNIQUE (name),
    CONSTRAINT locations_code_key UNIQUE (code)
);

ALTER TABLE public.locations OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.locations_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.locations_id_seq OWNER TO postgres;
ALTER SEQUENCE public.locations_id_seq OWNED BY public.locations.id;
ALTER TABLE ONLY public.locations ALTER COLUMN id SET DEFAULT nextval('public.locations_id_seq'::regclass);

CREATE INDEX idx_locations_public_id ON public.locations(public_id);
CREATE INDEX idx_locations_fts ON public.locations USING gin(fts);
CREATE INDEX idx_locations_features ON public.locations USING gin(features jsonb_path_ops);
CREATE INDEX idx_locations_coordinates ON public.locations USING gist(coordinates);
CREATE INDEX idx_locations_brand ON public.locations(brand_id);
CREATE INDEX idx_locations_type ON public.locations(location_type);
CREATE INDEX idx_locations_status ON public.locations(status);
CREATE INDEX idx_locations_city_state ON public.locations(city, state);

SELECT public.create_timestamps_trigger('locations');

-- Helper function to search locations by features
CREATE OR REPLACE FUNCTION public.search_locations_by_features(
    feature_filters jsonb,
    near_lat double precision DEFAULT NULL,
    near_lng double precision DEFAULT NULL,
    radius_miles double precision DEFAULT 50
)
RETURNS SETOF public.locations
LANGUAGE sql
STABLE
AS $$
    SELECT l.*
    FROM public.locations l
    WHERE 
        l.status = 'published'
        AND l.features @> feature_filters
        AND (
            near_lat IS NULL 
            OR extensions.ST_DWithin(
                l.coordinates,
                extensions.ST_SetSRID(extensions.ST_MakePoint(near_lng, near_lat), 4326)::extensions.geography,
                radius_miles * 1609.34
            )
        )
    ORDER BY 
        CASE 
            WHEN near_lat IS NOT NULL 
            THEN extensions.ST_Distance(
                l.coordinates,
                extensions.ST_SetSRID(extensions.ST_MakePoint(near_lng, near_lat), 4326)::extensions.geography
            )
            ELSE 0 
        END;
$$;

-- ============================================================================
-- POSTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.posts (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    message text,
    status varchar(255) DEFAULT NULL,
    pinned boolean DEFAULT false NOT NULL,
    promoted boolean DEFAULT false NOT NULL,
    flagged boolean DEFAULT false,
    approval_only boolean DEFAULT false,
    
    -- Counts
    like_count integer DEFAULT 0 NOT NULL,
    view_count integer DEFAULT 0,
    share_count integer DEFAULT 0,
    flag_count integer DEFAULT 0,
    
    -- Watch metrics
    total_watch_time integer DEFAULT 0,
    average_watch_time integer DEFAULT 0,
    watched_in_full_count integer DEFAULT 0,
    reach_count integer DEFAULT 0,
    
    -- Relations
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    postal_code_id integer REFERENCES public.postal_codes(id),
    file_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    
    -- Location
    geotag extensions.geometry(Point,4326),
    
    -- Media
    url varchar(255),
    has_file boolean,
    
    -- Timing
    live_time timestamptz,
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(message, ''))
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT posts_pkey PRIMARY KEY (id),
    CONSTRAINT posts_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.posts OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.posts_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.posts_id_seq OWNER TO postgres;
ALTER SEQUENCE public.posts_id_seq OWNED BY public.posts.id;
ALTER TABLE ONLY public.posts ALTER COLUMN id SET DEFAULT nextval('public.posts_id_seq'::regclass);

CREATE INDEX idx_posts_public_id ON public.posts(public_id);
CREATE INDEX idx_posts_profile ON public.posts(profile_id);
CREATE INDEX idx_posts_fts ON public.posts USING gin(fts);
CREATE INDEX idx_posts_created ON public.posts(created_at DESC);

SELECT public.create_timestamps_trigger('posts');

-- ============================================================================
-- LISTS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.lists (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(255),
    description text,
    product_count integer DEFAULT 0 NOT NULL,
    subscription_count integer DEFAULT 0,
    base boolean DEFAULT false,
    
    -- Relations
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    
    -- Media
    thumbnail_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    background_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    sort integer[] DEFAULT '{}'::integer[],
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(name, ''))
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT lists_pkey PRIMARY KEY (id),
    CONSTRAINT lists_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.lists OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.lists_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.lists_id_seq OWNER TO postgres;
ALTER SEQUENCE public.lists_id_seq OWNED BY public.lists.id;
ALTER TABLE ONLY public.lists ALTER COLUMN id SET DEFAULT nextval('public.lists_id_seq'::regclass);

CREATE INDEX idx_lists_public_id ON public.lists(public_id);

SELECT public.create_timestamps_trigger('lists');

-- ============================================================================
-- DEALS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.deals (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    expiration_date timestamp,
    release_date timestamp,
    percent_off real,
    dollar_off real,
    bogo_percent_off numeric(10,5),
    bogo_dollar_off real,
    total_deals integer,
    claimed_deals integer DEFAULT 0,
    expired boolean DEFAULT false,
    conditions text,
    header_message varchar(60),
    description text,
    is_medical boolean DEFAULT false,
    is_recreational boolean DEFAULT false,
    
    -- Relations
    product_id integer REFERENCES public.products(id),
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT deals_pkey PRIMARY KEY (id),
    CONSTRAINT deals_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.deals OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.deals_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.deals_id_seq OWNER TO postgres;
ALTER SEQUENCE public.deals_id_seq OWNED BY public.deals.id;
ALTER TABLE ONLY public.deals ALTER COLUMN id SET DEFAULT nextval('public.deals_id_seq'::regclass);

CREATE INDEX idx_deals_public_id ON public.deals(public_id);

SELECT public.create_timestamps_trigger('deals');

-- ============================================================================
-- GIVEAWAYS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.giveaways (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(255),
    description text,
    start_time timestamptz,
    end_time timestamptz,
    total_prizes integer,
    terms_url varchar(255) DEFAULT 'https://gethybrid.co/sweepstakes-terms-and-conditions',
    selected_winner boolean DEFAULT false,
    redeemed boolean DEFAULT false,
    entry_count integer DEFAULT 0 NOT NULL,
    winner_count integer DEFAULT 0,
    
    -- Relations
    product_id integer REFERENCES public.products(id),
    cover_id integer REFERENCES public.cloud_files(id),
    
    -- Full-text search
    fts tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(name, ''))
    ) STORED,
    
    -- Timestamps
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    CONSTRAINT giveaways_pkey PRIMARY KEY (id),
    CONSTRAINT giveaways_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.giveaways OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.giveaways_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.giveaways_id_seq OWNER TO postgres;
ALTER SEQUENCE public.giveaways_id_seq OWNED BY public.giveaways.id;
ALTER TABLE ONLY public.giveaways ALTER COLUMN id SET DEFAULT nextval('public.giveaways_id_seq'::regclass);

CREATE INDEX idx_giveaways_public_id ON public.giveaways(public_id);

SELECT public.create_timestamps_trigger('giveaways');

-- ============================================================================
-- MODERN NOTIFICATION SYSTEM
-- ============================================================================

-- Notification types (specific events)
CREATE TABLE IF NOT EXISTS public.notification_types (
    id serial PRIMARY KEY,
    code text UNIQUE NOT NULL,
    name text NOT NULL,
    description text,
    category public.notification_category NOT NULL DEFAULT 'activity',
    title_template text NOT NULL,
    body_template text NOT NULL,
    default_channels public.notification_channel[] DEFAULT '{in_app, push}',
    is_optional boolean DEFAULT true,
    priority integer DEFAULT 5,
    is_groupable boolean DEFAULT true,
    group_key text,
    action_url_template text,
    icon_name text,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.notification_types OWNER TO postgres;

-- Notification preferences
CREATE TABLE IF NOT EXISTS public.notification_preferences (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    social_channels public.notification_channel[],
    activity_channels public.notification_channel[],
    promotions_channels public.notification_channel[],
    system_channels public.notification_channel[],
    quiet_hours_enabled boolean DEFAULT false,
    quiet_hours_start time,
    quiet_hours_end time,
    quiet_hours_timezone text DEFAULT 'UTC',
    disabled_types text[] DEFAULT '{}',
    email_digest_frequency text DEFAULT 'daily' CHECK (email_digest_frequency IN ('never', 'daily', 'weekly')),
    is_muted_until timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT notification_preferences_public_id_key UNIQUE (public_id),
    UNIQUE(profile_id)
);

ALTER TABLE public.notification_preferences OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.notification_preferences_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.notification_preferences_id_seq OWNER TO postgres;
ALTER SEQUENCE public.notification_preferences_id_seq OWNED BY public.notification_preferences.id;
ALTER TABLE ONLY public.notification_preferences ALTER COLUMN id SET DEFAULT nextval('public.notification_preferences_id_seq'::regclass);

CREATE INDEX idx_notification_preferences_public_id ON public.notification_preferences(public_id);

SELECT public.create_timestamps_trigger('notification_preferences');

-- Push tokens (multi-device support)
CREATE TABLE IF NOT EXISTS public.push_tokens (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    token text NOT NULL UNIQUE,
    platform text NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
    device_id text,
    device_name text,
    app_version text,
    is_active boolean DEFAULT true,
    last_used_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now(),
    CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT push_tokens_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.push_tokens OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.push_tokens_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.push_tokens_id_seq OWNER TO postgres;
ALTER SEQUENCE public.push_tokens_id_seq OWNED BY public.push_tokens.id;
ALTER TABLE ONLY public.push_tokens ALTER COLUMN id SET DEFAULT nextval('public.push_tokens_id_seq'::regclass);

CREATE INDEX idx_push_tokens_public_id ON public.push_tokens(public_id);
CREATE INDEX idx_push_tokens_profile ON public.push_tokens(profile_id) WHERE is_active = true;

-- Notifications
CREATE TABLE IF NOT EXISTS public.notifications (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type_id integer NOT NULL REFERENCES public.notification_types(id),
    title text NOT NULL,
    body text NOT NULL,
    image_url text,
    action_url text,
    actor_id integer REFERENCES public.profiles(id) ON DELETE SET NULL,
    related_type text,
    related_id integer,
    data jsonb DEFAULT '{}',
    is_read boolean DEFAULT false,
    read_at timestamptz,
    is_seen boolean DEFAULT false,
    seen_at timestamptz,
    channels_sent public.notification_channel[] DEFAULT '{}',
    channels_failed public.notification_channel[] DEFAULT '{}',
    group_key text,
    group_count integer DEFAULT 1,
    expires_at timestamptz,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id),
    CONSTRAINT notifications_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.notifications OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.notifications_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.notifications_id_seq OWNER TO postgres;
ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;
ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);

CREATE INDEX idx_notifications_public_id ON public.notifications(public_id);
CREATE INDEX idx_notifications_profile ON public.notifications(profile_id);
CREATE INDEX idx_notifications_unread ON public.notifications(profile_id, is_read) WHERE is_read = false;
CREATE INDEX idx_notifications_type ON public.notifications(type_id);
CREATE INDEX idx_notifications_created ON public.notifications(created_at DESC);

-- Push queue
CREATE TABLE IF NOT EXISTS public.push_queue (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    notification_id integer REFERENCES public.notifications(id) ON DELETE CASCADE,
    push_token_id integer REFERENCES public.push_tokens(id) ON DELETE CASCADE,
    payload jsonb NOT NULL,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'cancelled')),
    attempts integer DEFAULT 0,
    max_attempts integer DEFAULT 3,
    send_at timestamptz DEFAULT now(),
    sent_at timestamptz,
    last_error text,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT push_queue_pkey PRIMARY KEY (id),
    CONSTRAINT push_queue_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.push_queue OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.push_queue_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.push_queue_id_seq OWNER TO postgres;
ALTER SEQUENCE public.push_queue_id_seq OWNED BY public.push_queue.id;
ALTER TABLE ONLY public.push_queue ALTER COLUMN id SET DEFAULT nextval('public.push_queue_id_seq'::regclass);

CREATE INDEX idx_push_queue_public_id ON public.push_queue(public_id);
CREATE INDEX idx_push_queue_pending ON public.push_queue(send_at) WHERE status = 'pending';

-- Insert default notification types
INSERT INTO public.notification_types (code, name, category, title_template, body_template, action_url_template, priority) VALUES
    ('new_follower', 'New Follower', 'social', '{actor_name} followed you', '{actor_name} started following you', '/profile/{actor_id}', 5),
    ('post_liked', 'Post Liked', 'social', '{actor_name} liked your post', '{actor_name} liked your post', '/post/{post_id}', 6),
    ('post_mentioned', 'Mentioned in Post', 'activity', '{actor_name} mentioned you', '{actor_name} mentioned you in a post', '/post/{post_id}', 4),
    ('new_comment', 'New Comment', 'activity', '{actor_name} commented', '{actor_name} commented on your post', '/post/{post_id}', 4),
    ('giveaway_entered', 'Giveaway Entry Confirmed', 'activity', 'Entry confirmed!', 'You''ve been entered in the giveaway', '/giveaway/{giveaway_id}', 5),
    ('giveaway_won', 'Giveaway Winner!', 'activity', 'Congratulations! 🎉', 'You won the giveaway!', '/giveaway/{giveaway_id}', 1),
    ('deal_expiring', 'Deal Expiring Soon', 'promotions', 'Deal ends soon', 'Don''t miss out - this deal expires in 24 hours', '/deal/{deal_id}', 6),
    ('new_product', 'New Product', 'promotions', 'New from {actor_name}', '{actor_name} just dropped a new product', '/product/{product_id}', 7),
    ('security_alert', 'Security Alert', 'system', 'Security Alert', 'New login detected from a new device', '/settings/security', 1),
    ('account_update', 'Account Update', 'system', 'Account Updated', 'Your account settings have been updated', '/settings', 3)
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- ADDRESSES TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.addresses (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    name varchar(255),
    address1 varchar(255),
    address2 varchar(255),
    postal_code_id integer REFERENCES public.postal_codes(id),
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT addresses_pkey PRIMARY KEY (id),
    CONSTRAINT addresses_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.addresses OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.addresses_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.addresses_id_seq OWNER TO postgres;
ALTER SEQUENCE public.addresses_id_seq OWNED BY public.addresses.id;
ALTER TABLE ONLY public.addresses ALTER COLUMN id SET DEFAULT nextval('public.addresses_id_seq'::regclass);

CREATE INDEX idx_addresses_public_id ON public.addresses(public_id);

SELECT public.create_timestamps_trigger('addresses');

-- ============================================================================
-- EXPLORE TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.explore (
    id integer NOT NULL,
    name varchar(255),
    description text,
    slug varchar(255),
    thumbnail_id integer REFERENCES public.cloud_files(id) ON DELETE SET NULL,
    start_date timestamp DEFAULT '2020-01-01 15:38:19.340007',
    end_date timestamp DEFAULT '2060-12-15 15:38:19.340007',
    "default" boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT explore_pkey PRIMARY KEY (id)
);

ALTER TABLE public.explore OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.explore_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.explore_id_seq OWNER TO postgres;
ALTER SEQUENCE public.explore_id_seq OWNED BY public.explore.id;
ALTER TABLE ONLY public.explore ALTER COLUMN id SET DEFAULT nextval('public.explore_id_seq'::regclass);

SELECT public.create_timestamps_trigger('explore');

CREATE TABLE IF NOT EXISTS public.explore_page (
    id integer NOT NULL,
    created_at timestamptz,
    updated_at timestamptz,
    CONSTRAINT explore_page_pkey PRIMARY KEY (id)
);

ALTER TABLE public.explore_page OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.explore_page_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.explore_page_id_seq OWNER TO postgres;
ALTER SEQUENCE public.explore_page_id_seq OWNED BY public.explore_page.id;
ALTER TABLE ONLY public.explore_page ALTER COLUMN id SET DEFAULT nextval('public.explore_page_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS public.explore_trending (
    id integer NOT NULL,
    name varchar(255),
    created_at timestamptz,
    updated_at timestamptz,
    CONSTRAINT explore_trending_pkey PRIMARY KEY (id)
);

ALTER TABLE public.explore_trending OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.explore_trending_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.explore_trending_id_seq OWNER TO postgres;
ALTER SEQUENCE public.explore_trending_id_seq OWNED BY public.explore_trending.id;
ALTER TABLE ONLY public.explore_trending ALTER COLUMN id SET DEFAULT nextval('public.explore_trending_id_seq'::regclass);

-- ============================================================================
-- SEND NOTIFICATION FUNCTION
-- ============================================================================

CREATE OR REPLACE FUNCTION public.send_notification(
    p_recipient_id integer,
    p_type_code text,
    p_actor_id integer DEFAULT NULL,
    p_related_type text DEFAULT NULL,
    p_related_id integer DEFAULT NULL,
    p_extra_data jsonb DEFAULT '{}'
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_notification_id integer;
    v_type public.notification_types%ROWTYPE;
    v_prefs public.notification_preferences%ROWTYPE;
    v_actor public.profiles%ROWTYPE;
    v_title text;
    v_body text;
    v_action_url text;
    v_channels public.notification_channel[];
BEGIN
    SELECT * INTO v_type FROM public.notification_types WHERE code = p_type_code;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unknown notification type: %', p_type_code;
    END IF;
    
    SELECT * INTO v_prefs FROM public.notification_preferences WHERE profile_id = p_recipient_id;
    
    IF v_prefs.disabled_types @> ARRAY[p_type_code] THEN
        RETURN NULL;
    END IF;
    
    IF v_prefs.is_muted_until IS NOT NULL AND v_prefs.is_muted_until > now() THEN
        RETURN NULL;
    END IF;
    
    IF p_actor_id IS NOT NULL THEN
        SELECT * INTO v_actor FROM public.profiles WHERE id = p_actor_id;
    END IF;
    
    v_title := v_type.title_template;
    v_body := v_type.body_template;
    v_action_url := v_type.action_url_template;
    
    IF v_actor.id IS NOT NULL THEN
        v_title := replace(v_title, '{actor_name}', coalesce(v_actor.display_name, v_actor.username, 'Someone'));
        v_body := replace(v_body, '{actor_name}', coalesce(v_actor.display_name, v_actor.username, 'Someone'));
        v_action_url := replace(v_action_url, '{actor_id}', v_actor.public_id::text);
    END IF;
    
    IF p_related_id IS NOT NULL THEN
        v_action_url := replace(v_action_url, '{' || p_related_type || '_id}', p_related_id::text);
    END IF;
    
    v_channels := CASE v_type.category
        WHEN 'social' THEN coalesce(v_prefs.social_channels, v_type.default_channels)
        WHEN 'activity' THEN coalesce(v_prefs.activity_channels, v_type.default_channels)
        WHEN 'promotions' THEN coalesce(v_prefs.promotions_channels, v_type.default_channels)
        WHEN 'system' THEN coalesce(v_prefs.system_channels, v_type.default_channels)
        ELSE v_type.default_channels
    END;
    
    INSERT INTO public.notifications (
        profile_id, type_id, title, body, action_url, actor_id,
        related_type, related_id, data, group_key
    ) VALUES (
        p_recipient_id, v_type.id, v_title, v_body, v_action_url, p_actor_id,
        p_related_type, p_related_id, p_extra_data,
        CASE WHEN v_type.is_groupable 
             THEN replace(coalesce(v_type.group_key, v_type.code), '{related_id}', coalesce(p_related_id::text, ''))
             ELSE NULL 
        END
    ) RETURNING id INTO v_notification_id;
    
    IF 'push' = ANY(v_channels) THEN
        INSERT INTO public.push_queue (notification_id, push_token_id, payload)
        SELECT 
            v_notification_id,
            pt.id,
            jsonb_build_object(
                'title', v_title,
                'body', v_body,
                'data', jsonb_build_object(
                    'notification_id', v_notification_id,
                    'action_url', v_action_url,
                    'type', p_type_code
                ) || p_extra_data
            )
        FROM public.push_tokens pt
        WHERE pt.profile_id = p_recipient_id
          AND pt.is_active = true;
    END IF;
    
    RETURN v_notification_id;
END;
$$;
