-- Secondary Tables
-- This migration creates supporting tables that depend on core tables
-- Updated: All foreign keys reference integer PKs, added public_id where appropriate
-- Updated: Uses profiles instead of users, locations instead of dispensary_locations
-- Removed: cannabis strain tables

-- ============================================================================
-- ANALYTICS & LOGGING TABLES
-- ============================================================================

-- Analytics posts table
CREATE TABLE IF NOT EXISTS public.analytics_posts (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    post_id integer REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    share_date timestamp,
    like_date timestamp,
    start_watching timestamp,
    end_watching timestamp,
    watch_duration integer,
    watch_in_full boolean DEFAULT false,
    view_section varchar(255),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT analytics_posts_pkey PRIMARY KEY (id),
    CONSTRAINT analytics_posts_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.analytics_posts OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.analytics_posts_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.analytics_posts_id_seq OWNER TO postgres;
ALTER SEQUENCE public.analytics_posts_id_seq OWNED BY public.analytics_posts.id;
ALTER TABLE ONLY public.analytics_posts ALTER COLUMN id SET DEFAULT nextval('public.analytics_posts_id_seq'::regclass);

CREATE INDEX idx_analytics_posts_public_id ON public.analytics_posts(public_id);

SELECT public.create_timestamps_trigger('analytics_posts');

-- Deletion log table
CREATE TABLE IF NOT EXISTS public.deletion_log (
    id integer NOT NULL,
    table_name text,
    record_id integer,
    record_public_id uuid,
    deleted_at timestamptz,
    deleted_data jsonb,
    CONSTRAINT deletion_log_pkey PRIMARY KEY (id)
);

ALTER TABLE public.deletion_log OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.deletion_log_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.deletion_log_id_seq OWNER TO postgres;
ALTER SEQUENCE public.deletion_log_id_seq OWNED BY public.deletion_log.id;
ALTER TABLE ONLY public.deletion_log ALTER COLUMN id SET DEFAULT nextval('public.deletion_log_id_seq'::regclass);

-- Post log table
CREATE TABLE IF NOT EXISTS public.post_log (
    id bigint NOT NULL,
    post_id integer REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    flagged boolean,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT post_log_pkey PRIMARY KEY (id)
);

ALTER TABLE public.post_log OWNER TO postgres;

ALTER TABLE public.post_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_log_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Post flags table
CREATE TABLE IF NOT EXISTS public.post_flags (
    id bigint NOT NULL,
    post_id integer REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    reason text,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT post_flags_pkey PRIMARY KEY (id)
);

ALTER TABLE public.post_flags OWNER TO postgres;

ALTER TABLE public.post_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_flags_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ============================================================================
-- PROFILE-RELATED TABLES
-- ============================================================================

-- Relationships (following) table
CREATE TABLE IF NOT EXISTS public.relationships (
    id integer NOT NULL,
    follower_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    followee_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role_id integer REFERENCES public.roles(id),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT relationships_pkey PRIMARY KEY (id),
    CONSTRAINT relationships_unique UNIQUE (follower_id, followee_id)
);

ALTER TABLE public.relationships OWNER TO postgres;

ALTER TABLE public.relationships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relationships_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_relationships_follower ON public.relationships(follower_id);
CREATE INDEX idx_relationships_followee ON public.relationships(followee_id);

SELECT public.create_timestamps_trigger('relationships');

-- Profile blocks table (was user_blocks)
CREATE TABLE IF NOT EXISTS public.profile_blocks (
    id bigint NOT NULL,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    blocked_profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT profile_blocks_pkey PRIMARY KEY (id),
    CONSTRAINT profile_blocks_unique UNIQUE (profile_id, blocked_profile_id)
);

ALTER TABLE public.profile_blocks OWNER TO postgres;

ALTER TABLE public.profile_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_blocks_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Profile admins table (was user_brand_admins)
CREATE TABLE IF NOT EXISTS public.profile_admins (
    id integer NOT NULL,
    admin_profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    managed_profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'admin' CHECK (role IN ('admin', 'editor', 'viewer')),
    created_at timestamptz DEFAULT now(),
    CONSTRAINT profile_admins_pkey PRIMARY KEY (id),
    CONSTRAINT profile_admins_unique UNIQUE (admin_profile_id, managed_profile_id)
);

ALTER TABLE public.profile_admins OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.profile_admins_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.profile_admins_id_seq OWNER TO postgres;
ALTER SEQUENCE public.profile_admins_id_seq OWNED BY public.profile_admins.id;
ALTER TABLE ONLY public.profile_admins ALTER COLUMN id SET DEFAULT nextval('public.profile_admins_id_seq'::regclass);

CREATE INDEX idx_profile_admins_admin ON public.profile_admins(admin_profile_id);
CREATE INDEX idx_profile_admins_managed ON public.profile_admins(managed_profile_id);

-- Profile delete requests table (was user_delete_requests)
CREATE TABLE IF NOT EXISTS public.profile_delete_requests (
    id bigint NOT NULL,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    email text,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT profile_delete_requests_pkey PRIMARY KEY (id)
);

ALTER TABLE public.profile_delete_requests OWNER TO postgres;

ALTER TABLE public.profile_delete_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_delete_requests_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ============================================================================
-- LOCATION-RELATED TABLES (was dispensary-related)
-- ============================================================================

-- Location employees table (was dispensary_employees)
CREATE TABLE IF NOT EXISTS public.location_employees (
    id bigint NOT NULL,
    location_id integer NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
    profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'staff' CHECK (role IN ('manager', 'staff', 'budtender')),
    is_approved boolean DEFAULT false,
    has_been_reviewed boolean DEFAULT false,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT location_employees_pkey PRIMARY KEY (id),
    CONSTRAINT location_employees_unique UNIQUE (location_id, profile_id)
);

ALTER TABLE public.location_employees OWNER TO postgres;
COMMENT ON COLUMN public.location_employees.is_approved IS 'whether the brand of the location has approved this employee';
COMMENT ON COLUMN public.location_employees.has_been_reviewed IS 'whether the brand has reviewed the employee request';

ALTER TABLE public.location_employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_employees_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_location_employees_location ON public.location_employees(location_id);
CREATE INDEX idx_location_employees_profile ON public.location_employees(profile_id);

SELECT public.create_timestamps_trigger('location_employees');

-- Location stashlists table (was dispensary_stashlists)
CREATE TABLE IF NOT EXISTS public.location_stashlists (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    location_id integer REFERENCES public.locations(id) ON DELETE CASCADE,
    list_id integer REFERENCES public.lists(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT location_stashlists_pkey PRIMARY KEY (id),
    CONSTRAINT location_stashlists_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.location_stashlists OWNER TO postgres;
COMMENT ON TABLE public.location_stashlists IS 'stashlists created for particular locations';

CREATE SEQUENCE IF NOT EXISTS public.location_stashlists_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.location_stashlists_id_seq OWNER TO postgres;
ALTER SEQUENCE public.location_stashlists_id_seq OWNED BY public.location_stashlists.id;
ALTER TABLE ONLY public.location_stashlists ALTER COLUMN id SET DEFAULT nextval('public.location_stashlists_id_seq'::regclass);

CREATE INDEX idx_location_stashlists_public_id ON public.location_stashlists(public_id);

-- Favorite locations table (was favorite_dispensaries)
CREATE TABLE IF NOT EXISTS public.favorite_locations (
    id bigint NOT NULL,
    location_id integer REFERENCES public.locations(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT favorite_locations_pkey PRIMARY KEY (id),
    CONSTRAINT favorite_locations_unique UNIQUE (profile_id, location_id)
);

ALTER TABLE public.favorite_locations OWNER TO postgres;

ALTER TABLE public.favorite_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_locations_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_favorite_locations_profile ON public.favorite_locations(profile_id);
CREATE INDEX idx_favorite_locations_location ON public.favorite_locations(location_id);

-- ============================================================================
-- PRODUCT & DEAL-RELATED TABLES
-- ============================================================================

-- Deal claims table
CREATE TABLE IF NOT EXISTS public.deal_claims (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    deal_id integer REFERENCES public.deals(id) ON DELETE CASCADE,
    redeemed boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT deal_claims_pkey PRIMARY KEY (id),
    CONSTRAINT deal_claims_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.deal_claims OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.deal_claims_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.deal_claims_id_seq OWNER TO postgres;
ALTER SEQUENCE public.deal_claims_id_seq OWNED BY public.deal_claims.id;
ALTER TABLE ONLY public.deal_claims ALTER COLUMN id SET DEFAULT nextval('public.deal_claims_id_seq'::regclass);

CREATE INDEX idx_deal_claims_public_id ON public.deal_claims(public_id);

SELECT public.create_timestamps_trigger('deal_claims');

-- Stash table
CREATE TABLE IF NOT EXISTS public.stash (
    id integer NOT NULL,
    product_id integer REFERENCES public.products(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    restash_id integer,
    restash_list_id integer REFERENCES public.lists(id),
    restash_post_id integer REFERENCES public.posts(id),
    restash_profile_id integer REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT stash_pkey PRIMARY KEY (id)
);

ALTER TABLE public.stash OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.stash_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.stash_id_seq OWNER TO postgres;
ALTER SEQUENCE public.stash_id_seq OWNED BY public.stash.id;
ALTER TABLE ONLY public.stash ALTER COLUMN id SET DEFAULT nextval('public.stash_id_seq'::regclass);

CREATE INDEX idx_stash_profile ON public.stash(profile_id);
CREATE INDEX idx_stash_product ON public.stash(product_id);

SELECT public.create_timestamps_trigger('stash');

-- Likes table
CREATE TABLE IF NOT EXISTS public.likes (
    id integer NOT NULL,
    post_id integer REFERENCES public.posts(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT likes_pkey PRIMARY KEY (id),
    CONSTRAINT likes_unique UNIQUE (post_id, profile_id)
);

ALTER TABLE public.likes OWNER TO postgres;

ALTER TABLE public.likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.likes_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE INDEX idx_likes_profile ON public.likes(profile_id);
CREATE INDEX idx_likes_post ON public.likes(post_id);

SELECT public.create_timestamps_trigger('likes');

-- Shop now table
CREATE TABLE IF NOT EXISTS public.shop_now (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id integer REFERENCES public.products(id) ON DELETE CASCADE,
    rank smallint,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT shop_now_pkey PRIMARY KEY (id),
    CONSTRAINT shop_now_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.shop_now OWNER TO postgres;
COMMENT ON TABLE public.shop_now IS 'Specific to the Shop Now section in Discover View';

CREATE SEQUENCE IF NOT EXISTS public.shop_now_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.shop_now_id_seq OWNER TO postgres;
ALTER SEQUENCE public.shop_now_id_seq OWNED BY public.shop_now.id;
ALTER TABLE ONLY public.shop_now ALTER COLUMN id SET DEFAULT nextval('public.shop_now_id_seq'::regclass);

CREATE INDEX idx_shop_now_public_id ON public.shop_now(public_id);

-- Featured items table
CREATE TABLE IF NOT EXISTS public.featured_items (
    id bigint NOT NULL,
    item_id integer NOT NULL,
    item_public_id uuid,
    item_type text NOT NULL,
    sort_order integer DEFAULT 0,
    created_by integer REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT featured_items_pkey PRIMARY KEY (id),
    CONSTRAINT featured_items_item_type_check CHECK (item_type = ANY (ARRAY['products', 'profiles', 'brands', 'posts', 'lists', 'giveaways', 'locations']))
);

ALTER TABLE public.featured_items OWNER TO postgres;
COMMENT ON COLUMN public.featured_items.item_id IS 'The integer ID of the featured item';
COMMENT ON COLUMN public.featured_items.item_public_id IS 'The public UUID of the featured item for API responses';
COMMENT ON COLUMN public.featured_items.item_type IS 'The table the item belongs to';
COMMENT ON COLUMN public.featured_items.sort_order IS 'Manual sort order set by an admin. Lower numbers appear first.';

ALTER TABLE public.featured_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.featured_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

SELECT public.create_timestamps_trigger('featured_items');

-- ============================================================================
-- GIVEAWAY-RELATED TABLES
-- ============================================================================

-- Giveaway entries table
CREATE TABLE IF NOT EXISTS public.giveaway_entries (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    giveaway_id integer REFERENCES public.giveaways(id) ON DELETE CASCADE,
    won boolean DEFAULT false,
    sent boolean DEFAULT false,
    shipping_notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT giveaway_entries_pkey PRIMARY KEY (id),
    CONSTRAINT giveaway_entries_public_id_key UNIQUE (public_id),
    CONSTRAINT giveaway_entries_unique UNIQUE (profile_id, giveaway_id)
);

ALTER TABLE public.giveaway_entries OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.giveaway_entries_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.giveaway_entries_id_seq OWNER TO postgres;
ALTER SEQUENCE public.giveaway_entries_id_seq OWNED BY public.giveaway_entries.id;
ALTER TABLE ONLY public.giveaway_entries ALTER COLUMN id SET DEFAULT nextval('public.giveaway_entries_id_seq'::regclass);

CREATE INDEX idx_giveaway_entries_public_id ON public.giveaway_entries(public_id);

SELECT public.create_timestamps_trigger('giveaway_entries');

-- Giveaway entries messages table
CREATE TABLE IF NOT EXISTS public.giveaway_entries_messages (
    id integer NOT NULL,
    public_id uuid NOT NULL DEFAULT gen_random_uuid(),
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    giveaway_entry_id integer REFERENCES public.giveaway_entries(id) ON DELETE CASCADE,
    message text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT giveaway_entries_messages_pkey PRIMARY KEY (id),
    CONSTRAINT giveaway_entries_messages_public_id_key UNIQUE (public_id)
);

ALTER TABLE public.giveaway_entries_messages OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.giveaway_entries_messages_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.giveaway_entries_messages_id_seq OWNER TO postgres;
ALTER SEQUENCE public.giveaway_entries_messages_id_seq OWNED BY public.giveaway_entries_messages.id;
ALTER TABLE ONLY public.giveaway_entries_messages ALTER COLUMN id SET DEFAULT nextval('public.giveaway_entries_messages_id_seq'::regclass);

CREATE INDEX idx_giveaway_entries_messages_public_id ON public.giveaway_entries_messages(public_id);

SELECT public.create_timestamps_trigger('giveaway_entries_messages');

-- ============================================================================
-- MISC TABLES
-- ============================================================================

-- Subscriptions lists table
CREATE TABLE IF NOT EXISTS public.subscriptions_lists (
    id integer NOT NULL,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    list_id integer REFERENCES public.lists(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT subscriptions_lists_pkey PRIMARY KEY (id),
    CONSTRAINT subscriptions_lists_unique UNIQUE (profile_id, list_id)
);

ALTER TABLE public.subscriptions_lists OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.subscriptions_lists_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.subscriptions_lists_id_seq OWNER TO postgres;
ALTER SEQUENCE public.subscriptions_lists_id_seq OWNED BY public.subscriptions_lists.id;
ALTER TABLE ONLY public.subscriptions_lists ALTER COLUMN id SET DEFAULT nextval('public.subscriptions_lists_id_seq'::regclass);

SELECT public.create_timestamps_trigger('subscriptions_lists');

-- Explore page sections table
CREATE TABLE IF NOT EXISTS public.explore_page_sections (
    id integer NOT NULL,
    explore_page_id integer REFERENCES public.explore_page(id),
    item varchar(255),
    sort integer,
    collection varchar(255),
    CONSTRAINT explore_page_sections_pkey PRIMARY KEY (id)
);

ALTER TABLE public.explore_page_sections OWNER TO postgres;

CREATE SEQUENCE IF NOT EXISTS public.explore_page_sections_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE public.explore_page_sections_id_seq OWNER TO postgres;
ALTER SEQUENCE public.explore_page_sections_id_seq OWNED BY public.explore_page_sections.id;
ALTER TABLE ONLY public.explore_page_sections ALTER COLUMN id SET DEFAULT nextval('public.explore_page_sections_id_seq'::regclass);
