-- Create normalized table for per-type preferences
CREATE TABLE IF NOT EXISTS public.profile_notification_type_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    notification_type_id integer REFERENCES public.notification_types(id) ON DELETE CASCADE,
    is_enabled boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    UNIQUE(profile_id, notification_type_id)
);

-- Enable RLS
ALTER TABLE public.profile_notification_type_settings ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own settings" 
    ON public.profile_notification_type_settings FOR SELECT 
    USING (profile_id = (SELECT id FROM public.profiles WHERE auth_id = auth.uid()));

CREATE POLICY "Users can update their own settings" 
    ON public.profile_notification_type_settings FOR UPDATE 
    USING (profile_id = (SELECT id FROM public.profiles WHERE auth_id = auth.uid()));

-- Trigger Function: Handle New Profile
CREATE OR REPLACE FUNCTION public.handle_new_profile_notification_settings()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profile_notification_type_settings (profile_id, notification_type_id, is_enabled)
    SELECT NEW.id, id, true
    FROM public.notification_types
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: On Profile Creation
DROP TRIGGER IF EXISTS on_profile_created_create_notification_settings ON public.profiles;
CREATE TRIGGER on_profile_created_create_notification_settings
    AFTER INSERT ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_profile_notification_settings();

-- Trigger Function: Handle New Notification Type
CREATE OR REPLACE FUNCTION public.handle_new_notification_type_settings()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profile_notification_type_settings (profile_id, notification_type_id, is_enabled)
    SELECT id, NEW.id, true
    FROM public.profiles
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: On Notification Type Creation
DROP TRIGGER IF EXISTS on_notification_type_created_create_settings ON public.notification_types;
CREATE TRIGGER on_notification_type_created_create_settings
    AFTER INSERT ON public.notification_types
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_notification_type_settings();

-- Backfill existing data (Respecting old disabled_types if present)
-- We use a DO block to handle the case where notification_preferences table might not exist or have data
DO $$
BEGIN
    -- Check if notification_preferences exists
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'notification_preferences') THEN
        INSERT INTO public.profile_notification_type_settings (profile_id, notification_type_id, is_enabled)
        SELECT 
            p.id, 
            nt.id, 
            CASE 
                WHEN np.disabled_types @> ARRAY[nt.code] THEN false 
                ELSE true 
            END
        FROM public.profiles p
        CROSS JOIN public.notification_types nt
        LEFT JOIN public.notification_preferences np ON np.profile_id = p.id
        ON CONFLICT (profile_id, notification_type_id) DO NOTHING;
    ELSE
        -- Simple backfill if old table doesn't exist
        INSERT INTO public.profile_notification_type_settings (profile_id, notification_type_id, is_enabled)
        SELECT p.id, nt.id, true
        FROM public.profiles p
        CROSS JOIN public.notification_types nt
        ON CONFLICT (profile_id, notification_type_id) DO NOTHING;
    END IF;
END $$;
