-- Drop tables if they exist to ensure clean creation (dev mode)
DROP TABLE IF EXISTS public.claimed_deals CASCADE;
DROP TABLE IF EXISTS public.deals CASCADE;

-- Create deals table
CREATE TABLE public.deals (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid DEFAULT gen_random_uuid() NOT NULL,
    location_id integer REFERENCES public.locations(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    deal_type text NOT NULL CHECK (deal_type IN ('percentage_off', 'amount_off', 'product_specific', 'bogo')),
    discount_value numeric,
    product_ids integer[],
    region_id integer REFERENCES public.regions(id) ON DELETE SET NULL,
    start_date timestamptz,
    end_date timestamptz,
    max_claims integer,
    claim_count integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT deals_pkey PRIMARY KEY (id),
    CONSTRAINT deals_public_id_key UNIQUE (public_id)
);

-- Create claimed_deals table
CREATE TABLE IF NOT EXISTS public.claimed_deals (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    public_id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    deal_id integer REFERENCES public.deals(id) ON DELETE CASCADE,
    claimed_at timestamptz DEFAULT now(),
    status text DEFAULT 'active' CHECK (status IN ('active', 'redeemed', 'expired')),
    redemption_code text NOT NULL,
    redeemed_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT claimed_deals_pkey PRIMARY KEY (id),
    CONSTRAINT claimed_deals_public_id_key UNIQUE (public_id),
    CONSTRAINT claimed_deals_redemption_code_key UNIQUE (redemption_code)
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_deals_location_id ON public.deals(location_id);
CREATE INDEX IF NOT EXISTS idx_deals_region_id ON public.deals(region_id);
CREATE INDEX IF NOT EXISTS idx_claimed_deals_profile_id ON public.claimed_deals(profile_id);
CREATE INDEX IF NOT EXISTS idx_claimed_deals_deal_id ON public.claimed_deals(deal_id);
CREATE INDEX IF NOT EXISTS idx_claimed_deals_status ON public.claimed_deals(status);

-- Add RLS policies (simplified for now, refine later)
ALTER TABLE public.deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.claimed_deals ENABLE ROW LEVEL SECURITY;

-- Everyone can read active deals
CREATE POLICY "Deals are viewable by everyone" ON public.deals
    FOR SELECT USING (true);

-- Only admins or brand owners can insert/update/delete deals (logic to be handled in app/edge functions mostly, but basic RLS here)
-- For now, allow authenticated users to create for simplicity in development, but strictly this should be restricted.
-- Assuming there's a way to check if user owns the location.
CREATE POLICY "Authenticated users can create deals" ON public.deals
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update deals" ON public.deals
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Users can read their own claimed deals
CREATE POLICY "Users can view own claimed deals" ON public.claimed_deals
    FOR SELECT USING (auth.uid() IN (SELECT auth_id FROM public.profiles WHERE id = profile_id));

-- Users can insert claimed deals (claim a deal)
CREATE POLICY "Users can claim deals" ON public.claimed_deals
    FOR INSERT WITH CHECK (auth.uid() IN (SELECT auth_id FROM public.profiles WHERE id = profile_id));

-- Users can update their own claimed deals (e.g. redeem)
CREATE POLICY "Users can update own claimed deals" ON public.claimed_deals
    FOR UPDATE USING (auth.uid() IN (SELECT auth_id FROM public.profiles WHERE id = profile_id));
