-- ============================================================================
-- COMMENT LIKES TABLE
-- Allows users to like comments on posts
-- ============================================================================

-- Ensure like_count column exists on post_comments
ALTER TABLE public.post_comments ADD COLUMN IF NOT EXISTS like_count integer DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.comment_likes (
    id integer NOT NULL,
    comment_id integer REFERENCES public.post_comments(id) ON DELETE CASCADE,
    profile_id integer REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT comment_likes_pkey PRIMARY KEY (id),
    CONSTRAINT comment_likes_unique UNIQUE (comment_id, profile_id)
);

ALTER TABLE public.comment_likes OWNER TO postgres;

-- Create sequence for auto-incrementing id
ALTER TABLE public.comment_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_likes_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON public.comment_likes(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_profile_id ON public.comment_likes(profile_id);

-- ============================================================================
-- TIMESTAMPS TRIGGER
-- ============================================================================

SELECT public.create_timestamps_trigger('comment_likes');

-- ============================================================================
-- TRIGGER TO UPDATE LIKE COUNT ON POST COMMENTS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.fn_update_comment_like_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE public.post_comments SET like_count = like_count + 1 WHERE id = NEW.comment_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE public.post_comments SET like_count = GREATEST(0, like_count - 1) WHERE id = OLD.comment_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_comment_like_count ON public.comment_likes;
CREATE TRIGGER trg_update_comment_like_count
    AFTER INSERT OR DELETE ON public.comment_likes
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_update_comment_like_count();

-- ============================================================================
-- RLS POLICIES
-- ============================================================================

ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;

-- Anyone can read comment likes
CREATE POLICY "comment_likes_select_policy" ON public.comment_likes
    FOR SELECT USING (true);

-- Authenticated users can insert their own likes
CREATE POLICY "comment_likes_insert_policy" ON public.comment_likes
    FOR INSERT WITH CHECK (
        profile_id IN (
            SELECT id FROM public.profiles WHERE auth_id = auth.uid()
        )
    );

-- Users can delete their own likes
CREATE POLICY "comment_likes_delete_policy" ON public.comment_likes
    FOR DELETE USING (
        profile_id IN (
            SELECT id FROM public.profiles WHERE auth_id = auth.uid()
        )
    );

-- ============================================================================
-- GRANTS
-- ============================================================================

GRANT ALL ON TABLE public.comment_likes TO anon;
GRANT ALL ON TABLE public.comment_likes TO authenticated;
GRANT ALL ON TABLE public.comment_likes TO service_role;
GRANT ALL ON SEQUENCE public.comment_likes_id_seq TO anon;
GRANT ALL ON SEQUENCE public.comment_likes_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.comment_likes_id_seq TO service_role;
